### ISSUE TITLE
Сломанный 2FA в новых версиях

### ISSUE THREAD

**Issue by bigenergy** [GravitLauncher/LauncherRuntime#112]
Решился на обновление с версии 5.2.12 до 5.3.5.
Появилась неизвестная мне проблема с юзерами у которых включен 2FA, если точнее - сцена с вводом 2FA кода не открывается и валится экзепшн.

Идентичная проблема: https://discord.com/channels/853340557522370561/853340558470414358/1023488180697190470
https://discord.com/channels/853340557522370561/853340558470414358/1019665673665916968

У меня по стактрейсу такие же ошибки, API работает без ошибок и возвращает все что нужно лаунчеру.

**Comment by microwin7** [comment]
https://discord.com/channels/853340557522370561/853340558470414359/1081946097305518080
