### ISSUE TITLE
Опциональный мод не удаляется после отключения

### ISSUE THREAD

**Issue by luckybl0ck** [GravitLauncher/LauncherRuntime#118]
Лаунчер не удаляет опциональный мод, если после скачивания отключить его в меню опциональных модов.

Релиз 5.4.1, рантайм 2.2.0.

**Comment by dimadencep** [comment]
Похоже, вы некорректно настроили их, смотрите [Опциональные моды](https://gravitlauncher.com/clientbuild/#%D0%BE%D0%BF%D1%86%D0%B8%D0%BE%D0%BD%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D0%BC%D0%BE%D0%B4%D1%8B)

**Comment by luckybl0ck** [comment]
Отрывок профиля с опциональными модами - https://paste.gg/p/anonymous/a2a2fd4d6f874999a30bbed520c3ee72. Названия файлов в папке mods соответствуют тем, что указаны в конфигурации профиля.

**Comment by luckybl0ck** [comment]
Когда воспроизводил проблему, то из всего списка опциональных модов выбирал лишь несколько, именно они и скачивались.

**Comment by microwin7** [comment]
> Порядок действий: выбираю опциональный мод -> клиент запускается с выбранным модом -> закрываю клиент -> отключаю опциональный мод -> мод не удаляется из папки и клиент опять запускается с ним.

А что с лаунчером в этот момент происходит как клиент запускается? Включен дебаг клиента? Или лаунчер перезапускаете

**Comment by luckybl0ck** [comment]
Дебаг клиента включен, лаунчер во время описанных мною выше действий не перезапускал, кнопку Сохранить при выключении мода также нажимать не забывал.

Конкретно в моем случае после этих действий клиент не запускается из-за конфликта модов BetterPVP и Xaeros Minimap. 
В вышеприведенной конфигурации они настроены как конфликтующие и не должны одновременно находиться у клиента в папке модов, что еще раз подтверждает проблему.

**Comment by luckybl0ck** [comment]
Проблема не воспроизводится на соседнем клиенте 1.7.10-forge (его список опциональных модов - https://paste.gg/p/anonymous/7a3c906139da4813a3036901a22d16d6), на нем функционал работает штатно, моды удаляются после их отключения и запуска клиента.

**Comment by microwin7** [comment]
> Проблема не воспроизводится на соседнем клиенте 1.7.10-forge (его список опциональных модов - https://paste.gg/p/anonymous/7a3c906139da4813a3036901a22d16d6), на нем функционал работает штатно, моды удаляются после их отключения и запуска клиента.

Можно увидеть разделы updateVerify и прочие схожие?

**Comment by luckybl0ck** [comment]
https://paste.gg/p/anonymous/429601c6da924413b0fe36332dc08b93 - проблема воспроизводится
https://paste.gg/p/anonymous/333aef0385a84e5d98fa409781792545 - проблема не воспроизводится

**Comment by microwin7** [comment]
> https://paste.gg/p/anonymous/429601c6da924413b0fe36332dc08b93 - проблема воспроизводится https://paste.gg/p/anonymous/333aef0385a84e5d98fa409781792545 - проблема не воспроизводится

А если полностью перезапустить лаунчер? к примеру до этого сохранить новые настройки опц модов и после перезапуска, в двух вариантах, тогда проблемы нет?

**Comment by luckybl0ck** [comment]
При перезапуске лаунчера после отключения мода проблема остается, мод при запуске клиента не удаляется.

**Comment by luckybl0ck** [comment]
![изображение](https://user-images.githubusercontent.com/79654924/235421612-67f3878f-3e8b-4cb1-8733-dd90bb7d33b3.png)
![mp4](https://user-images.githubusercontent.com/79654924/235421965-433fec89-1a8d-4167-b3c0-16a5e703e11f.gif)
