### ISSUE TITLE
Zero memory при перезагрузке лаунчера 

### ISSUE THREAD

**Issue by LoomeL** [GravitLauncher/LauncherRuntime#14]
[image](https://user-images.githubusercontent.com/44950511/80125075-f89e0580-85b2-11ea-894e-1519eaec5a94.png)

**Comment by gravit0** [comment]
0 значит автоматически, Леонадро убрал отображение справа и не куда стало вывести AUTO
Такое случается если вы переносите конфиг между версиями. На работоспособность запуска клиента это не влияет

**Comment by LoomeL** [comment]
> переносите конфиг между версиями
Это при рестарте лаунчера ващет

**Comment by LoomeL** [comment]
Странно, я вроде это писал ..
