### ISSUE TITLE
Лишние (Не задействованные) элементы

### ISSUE THREAD

**Issue by LoomeL** [GravitLauncher/LauncherRuntime#21]
![image](https://user-images.githubusercontent.com/44950511/80126170-862e2500-85b4-11ea-96a0-bffe502b5f21.png)

**Comment by LoomeL** [comment]
а именно 2 последних кружка

**Comment by gravit0** [comment]
Осталвлены для скачки своей Java и защиты
Если прям уж хочется - PR с классом для серых сфер, которые не используются
