### ISSUE TITLE
При нажатии на уведомление, оно закрывается. При последующем вызове уведомления происходит это:

### ISSUE THREAD

**Issue by LoomeL** [GravitLauncher/LauncherRuntime#23]
![image](https://user-images.githubusercontent.com/44950511/80126778-44ea4500-85b5-11ea-8ab7-4796edc8f70b.png)

**Comment by LoomeL** [comment]
И да, здесь нет zero memory, так как я потеребил слайдер

**Comment by JoCat** [comment]
О, давний баг, помню его))
