### ISSUE TITLE
warning: [deprecation]

### ISSUE THREAD

**Issue by IIIeX** [GravitLauncher/LauncherRuntime#36]
Phase 3: Clone runtime repository
Cloning into 'srcRuntime'...
remote: Enumerating objects: 142, done.
remote: Counting objects: 100% (142/142), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 2674 (delta 53), reused 113 (delta 37), pack-reused 2532
Receiving objects: 100% (2674/2674), 1.34 MiB | 1.01 MiB/s, done.
Resolving deltas: 100% (1237/1237), done.
/home/launcher/server_5.1.8/srcRuntime /home/launcher/server_5.1.8
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
Configuration on demand is an incubating feature.

Task :compileJava
/home/launcher/server_5.1.8/srcRuntime/src/main/java/pro/gravit/launcher/client/gui/overlay/OptionsOverlay.java:161: warning: [deprecation] getOptionalFile(String,OptionalType) in ClientProfile has been deprecated
                        OptionalFile file = selectedProfile.getOptionalFile(entryPair.name, entryPair.type);
/home/launcher/server_5.1.8/srcRuntime/src/main/java/pro/gravit/launcher/client/gui/overlay/OptionsOverlay.java:182: warning: [deprecation] type in OptionalFile has been deprecated
            type = optionalFile.type;
2 warnings

BUILD SUCCESSFUL in 12s
2 actionable tasks: 2 executed

openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode, sharing)

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/LauncherRuntime/pull/38
