### ISSUE TITLE
Не обрабатываемая ошибка.

### ISSUE THREAD

**Issue by Will0376** [GravitLauncher/LauncherRuntime#4]
СПАСИБО гравит за ахренительный код.
@radioegor146
@Zaxar163 
 будьте добры, пожалуйста - добавьте обработку траблы на 82 строке, которая и может вызывать луп лаунчера при обновлении 
Вот ссылка: https://github.com/GravitLauncher/LauncherRuntime/blob/master/src/main/java/pro/gravit/launcher/client/gui/scene/LoginScene.java#L82
ДЛЯ ГРАВИТА ОТДЕЛЬНО: НА 5.0.11 ТАКОЙ ХЕРНИ НЕ БЫЛО.
АПД от 13.04.2020(~0:54МСК). Был проведен эксперимент с последним билдом и настройками из коробки - всё-равно.
апд2(~1:03) Я устал это дерьмо терпеть и ливнул с гравита. СПАСИБО гравит

**Comment by gravit0** [comment]
https://discordapp.com/channels/478131707577368577/478133736680980481/699023794102075472
Проблема вообще не в этом и никак не связана с этим
Внимательнее изучайте информацию и не поддавайтесь панике

**Comment by Will0376** [comment]
Да глубоко насрать что даже дело не в этом. игнорировать ошибку - делать код дерьмово.
