### ISSUE TITLE
Не корректно работают и отображаются ссылки в runtime!

### ISSUE THREAD

**Issue by KlaydKladowayIgr** [GravitLauncher/LauncherRuntime#45]
Доброго времени суток! Занялся созданием макета дизайна под лаунчер. Как мне сказали в сообществе, чтобы создать ссылку нужно в конфиге JavaRuntime указать ссылки, сделал. Залезть в сам JavaRuntime.jar и в файле LoginScene прописать теги необходимым ссылкам, сделал. Добавил в JavaFXSceneBuilder fx:id для моей сцены. Собрал клиент - картина маслом. Иконки не отображаются, ссылки не работают, черти что! Хотя в JavaFXSceneBuilder всё корректно отображается. Помогите!
Вот, что добавил в LoginScene.java:
```
        if (application.guiModuleConfig.webURL != null)
            LookupHelper.<Hyperlink>lookup(layout, "#web").setOnAction((e) ->
                    application.openURL(application.guiModuleConfig.webURL));
```
Скрины fx:id и визуальная часть лаунчера ниже
![unknown2](https://user-images.githubusercontent.com/52831100/108108539-cc9fc380-70a1-11eb-9b31-1fee773668bc.png)
![unknown1](https://user-images.githubusercontent.com/52831100/108108541-cd385a00-70a1-11eb-8cd9-4ad1ad71d26b.png)
Вместо цифр, должны быть кнопки
![unknown](https://user-images.githubusercontent.com/52831100/108108543-cdd0f080-70a1-11eb-9024-8ebd11191426.png)

**Comment by KlaydKladowayIgr** [comment]
Так, я перезалил дизайн, кнопки появились, но не работают ссылки

**Comment by gravit0** [comment]
Убедитесь что вы корректно дополнили конфиг - в частности добавили вашему новому параметру webURL аннотации LauncherNetwork и LauncherInject - иначе лаунчсервер не впишет значение из конфига внутри конфига

**Comment by KlaydKladowayIgr** [comment]
В файле GuiModuleConfig. java добавил следующее:
	@LauncherInject("modules.javaruntime.webURL")
	public String webURL;

**Comment by gravit0** [comment]
Вот и ваша ошибка. Согласно форматированию параметра для launcherInject "modules.<названиемодуля>.<имя поля>" имя поля пишется в lowercase, т.е. modules.javaruntime.weburl

**Comment by KlaydKladowayIgr** [comment]
А,ок

**Comment by KlaydKladowayIgr** [comment]
Только, где я должен был искать документацию к оформлению?
