### ISSUE TITLE
Размытие SkinHead в окне выбора сервера

### ISSUE THREAD

**Issue by gravit0** [GravitLauncher/LauncherRuntime#5]
Выполнить скалирование через
image.getScaledInstance(imageWidth, imageHeight, java.awt.Image.SCALE_FAST);
Указав в качестве ширины и высоты ширину и высоту #avatar
Скалирование проводить после downloadSkinHead и до convertToFxImage

**Comment by JoCat** [comment]
👎

**Comment by Zaxar163** [comment]
30eb455
