### ISSUE TITLE
Баги рантайма

### ISSUE THREAD

**Issue by LoomeL** [GravitLauncher/LauncherRuntime#7]
Создал ишую для сбора багов визуальной части. По возможности буду фиксить. Просьба прикреплять скриншот и краткое описание бага.

**Comment by Scheshi** [comment]
![image](https://user-images.githubusercontent.com/47576867/79284122-98022080-7e6e-11ea-8b13-6a427e82fddc.png)

**Comment by Scheshi** [comment]
Пустота вместо скина.(или эт черный квадрат просто, я не понял еще)

**Comment by JoCat** [comment]
Могли накосячить с соотношением, я когда фикс делал тоже такое искусственно воспроизводил))

**Comment by JoCat** [comment]
Перепроверяй свой рантайм
![image](https://user-images.githubusercontent.com/13483132/79287174-99156b00-7ecb-11ea-8ec7-a2ffef9a4917.png)

**Comment by ijo42** [comment]
Скин на последнем рантайме был исправлен

**Comment by Zaxar163** [comment]
@Scheshi проверь первую багу на последнем ЛС и последнем рантайме.

**Comment by LoomeL** [comment]
> багов визуальной части

-_-

**Comment by ijo42** [comment]
Беда с переводом на eng/ru
Runtime и LaunchServer последние
https://i.imgur.com/bfb3sJx.png
https://i.imgur.com/EmupKps.png

**Comment by ijo42** [comment]
Беды с кнопкой опц. модов
https://paste.dimdev.org/exudihesev.hs

**Comment by gravit0** [comment]
Закрываю толстоissue
