### ISSUE TITLE
Не собирается (нет библиотек)

### ISSUE THREAD

**Issue by averyanalex** [GravitLauncher/LauncherRuntime#83]
* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find pro.gravit.launcher:launcher-core:5.2.3-SNAPSHOT.
     Searched in the following locations:
       - https://oss.sonatype.org/content/repositories/snapshots/pro/gravit/launcher/launcher-core/5.2.3-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/pro/gravit/launcher/launcher-core/5.2.3-SNAPSHOT/launcher-core-5.2.3-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/pro/gravit/launcher/launcher-core/5.2.3-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/pro/gravit/launcher/launcher-core/5.2.3-SNAPSHOT/launcher-core-5.2.3-SNAPSHOT.pom
     Required by:
         project :
Аналогично для pro.gravit.launcher:launcher-ws-api:5.2.3-SNAPSHOT и pro.gravit.launcher:launcher-client-api:5.2.3-SNAPSHOT

**Comment by averyanalex** [comment]
Изменил 5.2.3-SNAPSHOT на 5.2.3 в build.gradle, теперь либы скачиваются

**Comment by averyanalex** [comment]
Но теперь другая проблема
/home/container/srcRuntime/src/main/java/pro/gravit/launcher/client/gui/service/StateService.java:64: error: cannot find symbol
        return rawAuthResult.permissions.hasAction(name);
                                        ^
  symbol:   method hasAction(String)
  location: variable permissions of type ClientPermissions
1 error

**Comment by gravit0** [comment]
Старые снапшоты автоматически удаляются. Выложила еще раз
